### ISSUE TITLE
 assertion failed, available: 4, event type: 19

### ISSUE THREAD

**Issue by amolskh** [whitesock/open-replicator#10]
.11:13:48.020 [binlog-parser-1] ERROR c.g.c.o.b.impl.AbstractBinlogParser - failed to parse binlog 
java.lang.RuntimeException: assertion failed, available: 4, event type: 19
	at com.google.code.or.binlog.impl.FileBasedBinlogParser.doParse(FileBasedBinlogParser.java:140) ~[open-replicator-1.0.7.jar:na]
	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:244) ~[open-replicator-1.0.7.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

Can you tell me how to fix this?

**Comment by osheroff** [comment]
a little late to the party, but this is probably errors in handling mysql with binlog crc's on.  It's fixed over in https://github.com/zendesk/open-replicator
