### ISSUE TITLE
a error con't  be solved

### ISSUE THREAD

**Issue by dengdajun** [whitesock/open-replicator#19]
java.lang.RuntimeException: ErrorPacket[packetMarker=255,errorCode=1236,slash=#,sqlState=HY000,errorMessage=Slave can not handle replication events with the checksum that master is configured to log; the first event 'mysql-bin-log.000001' at 4, the last event read from 'D:\MySql\mysql-5.6.6-m9-winx64\log\mysql-bin-log.000001' at 120, the last byte read from 'D:\MySql\mysql-5.6.6-m9-winx64\log\mysql-bin-log.000001' at 120.]
	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:100)
	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:244)
	at java.lang.Thread.run(Thread.java:748)

this is my pom.xml
 <dependencies>
        <dependency>
            <groupId>open-replicator</groupId>
            <artifactId>open-replicator</artifactId>
            <version>1.0.7</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.3.11</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.1</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.44</version>
        </dependency>
    </dependencies>

and coding  just like your usage；
mysql version is 5.6.6
and my.ini config is
[mysql]
# 设置mysql客户端默认字符集
default-character-set=utf8 
[mysqld]
#skip-grant-tables
#设置3306端口
port = 3306 
# 设置mysql的安装目录
basedir=D:\MySql\mysql-5.6.6-m9-winx64
# 设置mysql数据库的数据的存放目录
datadir=D:\MySql\mysql-5.6.6-m9-winx64\data

log_bin=D:\MySql\mysql-5.6.6-m9-winx64\log\mysql-bin-log
server-id=1
binlog-format = row
# 允许最大连接数
max_connections=200
# 服务端使用的字符集默认为8比特编码的latin1字符集
character-set-server=utf8
# 创建新表时将使用的默认存储引擎
default-storage-engine=INNODB
collation-server=utf8_general_ci

**Comment by FishBaby** [comment]
TnT，I have the same error... if you had fix it , please tell me...  thank you ! thank you very much!!!
